version: '3.9'

services:
  backend_pointlojista:
    build:
      context: ./backend  # Caminho para o diretório do backend
    working_dir: /backend
    environment:
      DATABASE_URL: postgresql://postgres.ulcouxslkgvmjtujuysx:Ultrabem271!@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
    ports:
      - "5999:5999"
    volumes:
      - ./backend:/backend
    networks:
      - app-network

      
networks:
  app-network:
    driver: bridge  # Rede compartilhada entre o frontend e o backend
